version: "3"

services:
  frontend:
    build: ./frontend/learner-web
    container_name: LMS_frontend
    ports:
      - "5100:5100"
    environment:
      REACT_APP_BACKEND_URL: http://LMS_APIGateway:4200
    depends_on:
      - apigateway
    networks:
      - bk

  admin-dashboard:
    build: ./frontend/admin-dashboard
    container_name: LMS_admin
    ports:
      - "3000:3000"
    environment:
      REACT_APP_BACKEND_URL: http://LMS_APIGateway:4200
    depends_on:
      - apigateway
    networks:
      - bk

  apigateway:
    build: ./backend/api-gateway
    container_name: LMS_APIGateway
    ports:
      - "4200:4200"
    environment:
      REACT_APP_GATEWAY_PORT: 4200 
      PAYMENT_API: http://LMS_Payment:4204
      GATEWAY_API: http://LMS_APIGateway:4200
      COURSE_API: http://LMS_Course:4203
      LEARNER_API: http://LMS_Learner:4202
      AUTH_API: http://LMS_Auth:4201
    networks:
      - bk

  auth:
    build: ./backend/authentication-microservice
    container_name: LMS_Auth
    ports:
      - "4201:4201"
    environment:
      REACT_APP_GATEWAY_PORT: 4200
      PAYMENT_API: http://LMS_Payment:4204
      GATEWAY_API: http://LMS_APIGateway:4200 
      COURSE_API: http://LMS_Course:4203
      LEARNER_API: http://LMS_Learner:4202
      AUTH_API: http://LMS_Auth:4201
    depends_on:
      - apigateway
    networks:
      - bk

  learner:
    build: ./backend/learner-microservice
    container_name: LMS_Learner
    ports:
      - "4202:4202"
    environment:
      REACT_APP_GATEWAY_PORT: 4200
      PAYMENT_API: http://LMS_Payment:4204
      GATEWAY_API: http://LMS_APIGateway:4200
      COURSE_API: http://LMS_Course:4203
      LEARNER_API: http://LMS_Learner:4202
      AUTH_API: http://LMS_Auth:4201
    depends_on:
      - apigateway
      - course
    networks:
      - bk

  course:
    build: ./backend/course-microservice
    container_name: LMS_Course
    ports:
      - "4203:4203"
    environment:
      REACT_APP_GATEWAY_PORT: 4200
      PAYMENT_API: http://LMS_Payment:4204
      GATEWAY_API: http://LMS_APIGateway:4200
      COURSE_API: http://LMS_Course:4203
      LEARNER_API: http://LMS_Learner:4202
      AUTH_API: http://LMS_Auth:4201
    depends_on:
      - apigateway
    networks:
      - bk

  payment:
    build: ./backend/payment-microservice
    container_name: LMS_Payment
    ports:
      - "4204:4204"
    environment:
      REACT_APP_GATEWAY_PORT: 4200
      PAYMENT_API: http://LMS_Payment:4204
      GATEWAY_API: http://LMS_APIGateway:4200
      COURSE_API: http://LMS_Course:4203
      LEARNER_API: http://LMS_Learner:4202
      AUTH_API: http://LMS_Auth:4201
      MERCHANT_ID: 77wb3vb2qk9tsqd5
      PUBLIC_KEY: tgjnhxq4mjn9wz6c
      PRIVATE_KEY: ebf744219a9166c14db77ade45bd46e6
    depends_on:
      - apigateway
    networks:
      - bk

networks:
  bk:
    driver: bridge

# run below command in terminal
# docker compose up -d
# docker build -t herbal-medicine-selling-platform-frontend .
