apiVersion: v1
kind: Service
metadata:
  name: LMS
spec:
  ports:
  - name: frontend
    port: 5100
    protocol: TCP
    targetPort: 5100
  - name: admin-dashboard
    port: 3000
    protocol: TCP
    targetPort: 3000
  - name: apigateway
    port: 4200
    protocol: TCP
    targetPort: 4200
  - name: auth
    port: 4201
    protocol: TCP
    targetPort: 4201
  - name: learner
    port: 4202
    protocol: TCP
    targetPort: 4202
  - name: course
    port: 4203
    protocol: TCP
    targetPort: 4203
  - name: payment
    port: 4204
    protocol: TCP
    targetPort: 4204   
  selector:
    app: LMS
  type: LoadBalancer
status:
  loadBalancer: {}
 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: LMS
  name: LMS
spec:
  replicas: 1
  selector:
    matchLabels:
      app: LMS
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: LMS
    spec:
      containers:
      - name: frontend
        image: sanjanadinith/lms-frontend
        imagePullPolicy: Always
        ports:
        - containerPort: 5100
          protocol: TCP
        resources: {}
      - name: admin-dashboard
        image: sanjanadinith/lms-admin-dashboard
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
          protocol: TCP
        resources: {}
      - name: apigateway
        image: sanjanadinith/lms-apigateway
        imagePullPolicy: Always
        ports:
        - containerPort: 4200
          protocol: TCP
        resources: {}
      - name: auth
        image: sanjanadinith/lms-auth
        imagePullPolicy: Always
        ports:
        - containerPort: 4201
          protocol: TCP
        resources: {}
      - name: learner
        image: sanjanadinith/lms-learner
        imagePullPolicy: Always
        ports:
        - containerPort: 4202
          protocol: TCP
        resources: {}
      - name: course
        image: sanjanadinith/lms-course
        imagePullPolicy: Always
        ports:
        - containerPort: 4203
          protocol: TCP
        resources: {}
      - name: payment
        image: sanjanadinith/lms-payment
        imagePullPolicy: Always
        ports:
        - containerPort: 4204
          protocol: TCP
        resources: {}
      restartPolicy: Always
status: {}

# kubectl apply -f behethkade.yaml
# kubectl delete -f behethkade.yaml