export const timetable = [
    {
        day: "Monday",
        timeSlots: [
            { startTime: "08:00 AM", endTime: "08:30 AM", isAvailable: true },
            { startTime: "08:30 AM", endTime: "09:00 AM", isAvailable: true },
            { startTime: "09:00 AM", endTime: "09:30 AM", isAvailable: true },
            { startTime: "09:30 AM", endTime: "10:00 AM", isAvailable: true },
            { startTime: "10:00 AM", endTime: "10:30 AM", isAvailable: true },
            { startTime: "10:30 AM", endTime: "11:00 AM", isAvailable: true },
            { startTime: "11:00 AM", endTime: "11:30 AM", isAvailable: true },
            { startTime: "11:30 AM", endTime: "12:00 PM", isAvailable: true },
            { startTime: "12:00 PM", endTime: "12:30 PM", isAvailable: true },
            { startTime: "12:30 PM", endTime: "01:00 PM", isAvailable: true },
            { startTime: "01:00 PM", endTime: "01:30 PM", isAvailable: true },
            { startTime: "01:30 PM", endTime: "02:00 PM", isAvailable: true },
            { startTime: "02:00 PM", endTime: "02:30 PM", isAvailable: true },
            { startTime: "02:30 PM", endTime: "03:00 PM", isAvailable: true },
            { startTime: "03:00 PM", endTime: "03:30 PM", isAvailable: true },
            { startTime: "03:30 PM", endTime: "04:00 PM", isAvailable: true },
            { startTime: "04:00 PM", endTime: "04:30 PM", isAvailable: true },
            { startTime: "04:30 PM", endTime: "05:00 PM", isAvailable: true },
            { startTime: "05:00 PM", endTime: "05:30 PM", isAvailable: true },
            { startTime: "05:30 PM", endTime: "06:00 PM", isAvailable: true },
            { startTime: "06:00 PM", endTime: "06:30 PM", isAvailable: true },
            { startTime: "06:30 PM", endTime: "07:00 PM", isAvailable: true },
            { startTime: "07:00 PM", endTime: "07:30 PM", isAvailable: true },
            { startTime: "07:30 PM", endTime: "08:00 PM", isAvailable: true },

        ],
    },
    {
        day: "Tuesday",
        timeSlots: [
            { startTime: "08:00 AM", endTime: "08:30 AM", isAvailable: true },
            { startTime: "08:30 AM", endTime: "09:00 AM", isAvailable: true },
            { startTime: "09:00 AM", endTime: "09:30 AM", isAvailable: true },
            { startTime: "09:30 AM", endTime: "10:00 AM", isAvailable: true },
            { startTime: "10:00 AM", endTime: "10:30 AM", isAvailable: true },
            { startTime: "10:30 AM", endTime: "11:00 AM", isAvailable: true },
            { startTime: "11:00 AM", endTime: "11:30 AM", isAvailable: true },
            { startTime: "11:30 AM", endTime: "12:00 PM", isAvailable: true },
            { startTime: "12:00 PM", endTime: "12:30 PM", isAvailable: true },
            { startTime: "12:30 PM", endTime: "01:00 PM", isAvailable: true },
            { startTime: "01:00 PM", endTime: "01:30 PM", isAvailable: true },
            { startTime: "01:30 PM", endTime: "02:00 PM", isAvailable: true },
            { startTime: "02:00 PM", endTime: "02:30 PM", isAvailable: true },
            { startTime: "02:30 PM", endTime: "03:00 PM", isAvailable: true },
            { startTime: "03:00 PM", endTime: "03:30 PM", isAvailable: true },
            { startTime: "03:30 PM", endTime: "04:00 PM", isAvailable: true },
            { startTime: "04:00 PM", endTime: "04:30 PM", isAvailable: true },
            { startTime: "04:30 PM", endTime: "05:00 PM", isAvailable: true },
            { startTime: "05:00 PM", endTime: "05:30 PM", isAvailable: true },
            { startTime: "05:30 PM", endTime: "06:00 PM", isAvailable: true },
            { startTime: "06:00 PM", endTime: "06:30 PM", isAvailable: true },
            { startTime: "06:30 PM", endTime: "07:00 PM", isAvailable: true },
            { startTime: "07:00 PM", endTime: "07:30 PM", isAvailable: true },
            { startTime: "07:30 PM", endTime: "08:00 PM", isAvailable: true },

        ],
    },
    {
        day: "Wednesday",
        timeSlots: [
            { startTime: "08:00 AM", endTime: "08:30 AM", isAvailable: true },
            { startTime: "08:30 AM", endTime: "09:00 AM", isAvailable: true },
            { startTime: "09:00 AM", endTime: "09:30 AM", isAvailable: true },
            { startTime: "09:30 AM", endTime: "10:00 AM", isAvailable: true },
            { startTime: "10:00 AM", endTime: "10:30 AM", isAvailable: true },
            { startTime: "10:30 AM", endTime: "11:00 AM", isAvailable: true },
            { startTime: "11:00 AM", endTime: "11:30 AM", isAvailable: true },
            { startTime: "11:30 AM", endTime: "12:00 PM", isAvailable: true },
            { startTime: "12:00 PM", endTime: "12:30 PM", isAvailable: true },
            { startTime: "12:30 PM", endTime: "01:00 PM", isAvailable: true },
            { startTime: "01:00 PM", endTime: "01:30 PM", isAvailable: true },
            { startTime: "01:30 PM", endTime: "02:00 PM", isAvailable: true },
            { startTime: "02:00 PM", endTime: "02:30 PM", isAvailable: true },
            { startTime: "02:30 PM", endTime: "03:00 PM", isAvailable: true },
            { startTime: "03:00 PM", endTime: "03:30 PM", isAvailable: true },
            { startTime: "03:30 PM", endTime: "04:00 PM", isAvailable: true },
            { startTime: "04:00 PM", endTime: "04:30 PM", isAvailable: true },
            { startTime: "04:30 PM", endTime: "05:00 PM", isAvailable: true },
            { startTime: "05:00 PM", endTime: "05:30 PM", isAvailable: true },
            { startTime: "05:30 PM", endTime: "06:00 PM", isAvailable: true },
            { startTime: "06:00 PM", endTime: "06:30 PM", isAvailable: true },
            { startTime: "06:30 PM", endTime: "07:00 PM", isAvailable: true },
            { startTime: "07:00 PM", endTime: "07:30 PM", isAvailable: true },
            { startTime: "07:30 PM", endTime: "08:00 PM", isAvailable: true },

        ],
    },
    {
        day: "Thursday",
        timeSlots: [
            { startTime: "08:00 AM", endTime: "08:30 AM", isAvailable: true },
            { startTime: "08:30 AM", endTime: "09:00 AM", isAvailable: true },
            { startTime: "09:00 AM", endTime: "09:30 AM", isAvailable: true },
            { startTime: "09:30 AM", endTime: "10:00 AM", isAvailable: true },
            { startTime: "10:00 AM", endTime: "10:30 AM", isAvailable: true },
            { startTime: "10:30 AM", endTime: "11:00 AM", isAvailable: true },
            { startTime: "11:00 AM", endTime: "11:30 AM", isAvailable: true },
            { startTime: "11:30 AM", endTime: "12:00 PM", isAvailable: true },
            { startTime: "12:00 PM", endTime: "12:30 PM", isAvailable: true },
            { startTime: "12:30 PM", endTime: "01:00 PM", isAvailable: true },
            { startTime: "01:00 PM", endTime: "01:30 PM", isAvailable: true },
            { startTime: "01:30 PM", endTime: "02:00 PM", isAvailable: true },
            { startTime: "02:00 PM", endTime: "02:30 PM", isAvailable: true },
            { startTime: "02:30 PM", endTime: "03:00 PM", isAvailable: true },
            { startTime: "03:00 PM", endTime: "03:30 PM", isAvailable: true },
            { startTime: "03:30 PM", endTime: "04:00 PM", isAvailable: true },
            { startTime: "04:00 PM", endTime: "04:30 PM", isAvailable: true },
            { startTime: "04:30 PM", endTime: "05:00 PM", isAvailable: true },
            { startTime: "05:00 PM", endTime: "05:30 PM", isAvailable: true },
            { startTime: "05:30 PM", endTime: "06:00 PM", isAvailable: true },
            { startTime: "06:00 PM", endTime: "06:30 PM", isAvailable: true },
            { startTime: "06:30 PM", endTime: "07:00 PM", isAvailable: true },
            { startTime: "07:00 PM", endTime: "07:30 PM", isAvailable: true },
            { startTime: "07:30 PM", endTime: "08:00 PM", isAvailable: true },

        ],
    },
    {
        day: "Friday",
        timeSlots: [
            { startTime: "08:00 AM", endTime: "08:30 AM", isAvailable: true },
            { startTime: "08:30 AM", endTime: "09:00 AM", isAvailable: true },
            { startTime: "09:00 AM", endTime: "09:30 AM", isAvailable: true },
            { startTime: "09:30 AM", endTime: "10:00 AM", isAvailable: true },
            { startTime: "10:00 AM", endTime: "10:30 AM", isAvailable: true },
            { startTime: "10:30 AM", endTime: "11:00 AM", isAvailable: true },
            { startTime: "11:00 AM", endTime: "11:30 AM", isAvailable: true },
            { startTime: "11:30 AM", endTime: "12:00 PM", isAvailable: true },
            { startTime: "12:00 PM", endTime: "12:30 PM", isAvailable: true },
            { startTime: "12:30 PM", endTime: "01:00 PM", isAvailable: true },
            { startTime: "01:00 PM", endTime: "01:30 PM", isAvailable: true },
            { startTime: "01:30 PM", endTime: "02:00 PM", isAvailable: true },
            { startTime: "02:00 PM", endTime: "02:30 PM", isAvailable: true },
            { startTime: "02:30 PM", endTime: "03:00 PM", isAvailable: true },
            { startTime: "03:00 PM", endTime: "03:30 PM", isAvailable: true },
            { startTime: "03:30 PM", endTime: "04:00 PM", isAvailable: true },
            { startTime: "04:00 PM", endTime: "04:30 PM", isAvailable: true },
            { startTime: "04:30 PM", endTime: "05:00 PM", isAvailable: true },
            { startTime: "05:00 PM", endTime: "05:30 PM", isAvailable: true },
            { startTime: "05:30 PM", endTime: "06:00 PM", isAvailable: true },
            { startTime: "06:00 PM", endTime: "06:30 PM", isAvailable: true },
            { startTime: "06:30 PM", endTime: "07:00 PM", isAvailable: true },
            { startTime: "07:00 PM", endTime: "07:30 PM", isAvailable: true },
            { startTime: "07:30 PM", endTime: "08:00 PM", isAvailable: true },

        ],
    },
    {
        day: "Saturday",
        timeSlots: [
            { startTime: "08:00 AM", endTime: "08:30 AM", isAvailable: true },
            { startTime: "08:30 AM", endTime: "09:00 AM", isAvailable: true },
            { startTime: "09:00 AM", endTime: "09:30 AM", isAvailable: true },
            { startTime: "09:30 AM", endTime: "10:00 AM", isAvailable: true },
            { startTime: "10:00 AM", endTime: "10:30 AM", isAvailable: true },
            { startTime: "10:30 AM", endTime: "11:00 AM", isAvailable: true },
            { startTime: "11:00 AM", endTime: "11:30 AM", isAvailable: true },
            { startTime: "11:30 AM", endTime: "12:00 PM", isAvailable: true },
            { startTime: "12:00 PM", endTime: "12:30 PM", isAvailable: true },
            { startTime: "12:30 PM", endTime: "01:00 PM", isAvailable: true },
            { startTime: "01:00 PM", endTime: "01:30 PM", isAvailable: true },
            { startTime: "01:30 PM", endTime: "02:00 PM", isAvailable: true },
            { startTime: "02:00 PM", endTime: "02:30 PM", isAvailable: true },
            { startTime: "02:30 PM", endTime: "03:00 PM", isAvailable: true },
            { startTime: "03:00 PM", endTime: "03:30 PM", isAvailable: true },
            { startTime: "03:30 PM", endTime: "04:00 PM", isAvailable: true },
            { startTime: "04:00 PM", endTime: "04:30 PM", isAvailable: true },
            { startTime: "04:30 PM", endTime: "05:00 PM", isAvailable: true },
            { startTime: "05:00 PM", endTime: "05:30 PM", isAvailable: true },
            { startTime: "05:30 PM", endTime: "06:00 PM", isAvailable: true },
            { startTime: "06:00 PM", endTime: "06:30 PM", isAvailable: true },
            { startTime: "06:30 PM", endTime: "07:00 PM", isAvailable: true },
            { startTime: "07:00 PM", endTime: "07:30 PM", isAvailable: true },
            { startTime: "07:30 PM", endTime: "08:00 PM", isAvailable: true },

        ],
    },
    {
        day: "Sunday",
        timeSlots: [
            { startTime: "08:00 AM", endTime: "08:30 AM", isAvailable: true },
            { startTime: "08:30 AM", endTime: "09:00 AM", isAvailable: true },
            { startTime: "09:00 AM", endTime: "09:30 AM", isAvailable: true },
            { startTime: "09:30 AM", endTime: "10:00 AM", isAvailable: true },
            { startTime: "10:00 AM", endTime: "10:30 AM", isAvailable: true },
            { startTime: "10:30 AM", endTime: "11:00 AM", isAvailable: true },
            { startTime: "11:00 AM", endTime: "11:30 AM", isAvailable: true },
            { startTime: "11:30 AM", endTime: "12:00 PM", isAvailable: true },
            { startTime: "12:00 PM", endTime: "12:30 PM", isAvailable: true },
            { startTime: "12:30 PM", endTime: "01:00 PM", isAvailable: true },
            { startTime: "01:00 PM", endTime: "01:30 PM", isAvailable: true },
            { startTime: "01:30 PM", endTime: "02:00 PM", isAvailable: true },
            { startTime: "02:00 PM", endTime: "02:30 PM", isAvailable: true },
            { startTime: "02:30 PM", endTime: "03:00 PM", isAvailable: true },
            { startTime: "03:00 PM", endTime: "03:30 PM", isAvailable: true },
            { startTime: "03:30 PM", endTime: "04:00 PM", isAvailable: true },
            { startTime: "04:00 PM", endTime: "04:30 PM", isAvailable: true },
            { startTime: "04:30 PM", endTime: "05:00 PM", isAvailable: true },
            { startTime: "05:00 PM", endTime: "05:30 PM", isAvailable: true },
            { startTime: "05:30 PM", endTime: "06:00 PM", isAvailable: true },
            { startTime: "06:00 PM", endTime: "06:30 PM", isAvailable: true },
            { startTime: "06:30 PM", endTime: "07:00 PM", isAvailable: true },
            { startTime: "07:00 PM", endTime: "07:30 PM", isAvailable: true },
            { startTime: "07:30 PM", endTime: "08:00 PM", isAvailable: true },

        ],
    },


];

export default timetable;